### ISSUE TITLE
Error comparing ROOT files

### ISSUE THREAD

**Issue by beojan** [FAST-HEP/scikit-validate#38]
When comparing two ROOT files, I get the error:

```
Testing 332 distributions
Traceback (most recent call last):
  File "/bin/sv_root_diff", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/skvalidate/commands/root_diff.py", line 130, in cli
    for name, comparison in compare.compare_two_root_files(file_under_test, reference_file):
  File "/usr/lib/python3.9/site-packages/skvalidate/compare/__init__.py", line 63, in compare_two_root_files
    value1 = load_value(name, file1, keys1)
  File "/usr/lib/python3.9/site-packages/skvalidate/compare/__init__.py", line 111, in load_value
    value = ak.flatten(value)
  File "/usr/lib/python3.9/site-packages/awkward/operations/structure.py", line 1592, in flatten
    layout = ak.operations.convert.to_layout(
  File "/usr/lib/python3.9/site-packages/awkward/operations/convert.py", line 1882, in to_layout
    raise TypeError(
TypeError: <TH1D (version 3) at 0x7ff90be616d0> cannot be converted into an Awkward Array

(https://github.com/scikit-hep/awkward-1.0/blob/1.1.2/src/awkward/operations/convert.py#L1884)
```

**Comment by kreczko** [comment]
Hi @beojan,

Thank you for reporting the issue. Indeed, histograms are currently not covered by the comparison.

Uproot now supports [boost_histogram conversion](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TH1.Histogram.html#to-boost) and [hist](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TH1.Histogram.html#to-hist) but neither supports comparisons well.

Since histograms also include uncertainties, they are a bit harder to compare with just numpy arrays.
Would it be sufficient for your use-case to just look at the values of the histogram?

**Comment by beojan** [comment]
In this case it would be enough to just ignore the histograms and compare only the trees.

**Comment by kreczko** [comment]
@beojan just released version 0.4.1 which should contain the fix. It should be available in a few minutes via pypi.

Could you please give it a go and check if it fixes the issue for you?

**Comment by beojan** [comment]
It still doesn't work because I also have `TParameters`. Maybe you could just ignore objects you can't read (perhaps with a warning)?

**Comment by kreczko** [comment]
I was hoping for at least some support for hists with 0.4.1, but you are right, all other cases need to be caught as well.
Will prepare a more general solution for 0.4.2.

**Comment by beojan** [comment]
Thanks!
